# Le dice a Nixpacks/Railpack que la raíz de la aplicación es la carpeta BACKEND
[setup]
# Establece el directorio de trabajo para todas las operaciones de compilación y despliegue
working_dir = "BACKEND" 

# Forzamos la detección de Python
[phases]
install = 'pip install -r requirements.txt'
